#!/usr/bin/env bash
# Displays a list of current running processes
# Must show all the processes for all users including those that might have tty
# display in user oriented format
# show process hirechy

ps -auxf

