#!/usr/bin/env bash
# Prints To infinity and beyond indefinitely
# Printa I am invincible!!! when receiving a SIGTERM signal

while true
do
echo "To infinity and beyond"
sleep 2
trap 'echo "I am invincible!!!"' SIGTERM
done

