#!/usr/bin/env bash
# Prints all digits between 1 and 20 except
# In iteration 4 where it prints 4 then a new line followe by:
# bad luck from China
# In iteration 9 where it prints 9 then a new line followed by:
# bad luck from Japan
# In iteration 17 where it prints 17 then new line followed by:
# bad luck from Italy

counter=1

while [ $counter -le 20 ]
do
case $counter in
4)
printf "4\nbad luck from China\n"
;;
9)
printf "9\nbad luck from Japan\n"
;;
17)
printf "17\nbad luck from Italy\n"
;;
*)
echo "$counter"
;;
esac
counter=$((counter + 1))
done

