#!/usr/bin/env bash
# checks if a file exists
# prints "school file exists" if it exists
# prints "school file does not exist" if it doesn't

# if the file exists
# prints "shool file is empty" if the file is empty
# prints "school file is not empty" if the file is not empty
# prints "school is a regular file" if it is a regular file

FILE="school"

if [ -e "$FILE" ];
then
echo "school file exists"
if [ -s "$FILE" ];
then echo "school file is not empty"
else echo "school file is empty"
fi
if [ -f "$FILE" ];
then echo "school is a regular file"
fi
else
echo "school file does not exist"
fi

