#!/bin/bash

# Update the system and install ufw
sudo apt-get update
sudo apt-get install ufw

# Allow incoming traffic for SSH (port 22), HTTPS SSL (port 443), and HTTP (port 80)
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp

# Deny all other incoming traffic
sudo ufw default deny incoming

# Enable ufw
sudo ufw enable

# Check the status of ufw
sudo ufw status
